worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    # Upstream for the web application
    upstream web_app {
        server web:8000;
    }

    # Upstream for Grafana
    upstream grafana_service {
        server grafana:3000;
    }

    # Upstream for Prometheus
    upstream prometheus_service {
        server prometheus:9090;
    }

    server {
        listen 80;
        server_name 15.237.213.190 localhost; # Use the provided IP and localhost

        # Root endpoint for the application
        location / {
            proxy_pass http://web_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Monitoring endpoint for Grafana
        location /monitoring/ {
            proxy_pass http://grafana_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            # Required for Grafana live to work behind proxy
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Endpoint for Prometheus UI
        location /prometheus/ {
            proxy_pass http://prometheus_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
